### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Abdulaev** [ruanyl/dts-loader#1]
Please, could you add an example? Because my MFE doesn't generate the tarball

**Comment by ruanyl** [comment]
Hi @Abdulaev, have you seen any errors? or can you share your setup?
And did you get the output types? or just didn't see the tarball?

**Comment by ruanyl** [comment]
I just found that generating tarball isn't included in `dts-loader`, it's part of my other micro-frontend tool which still under development.
I'm sorry for the confusion caused by the README.

**Comment by ruanyl** [comment]
I think I'm gonna add this feature(tarball generation) to `WebpackRemoteTypesPlugin`.

**Comment by Abdulaev** [comment]
Yeah, thanks. So, it would be great if you could add something like CLI to generate & download types from remote. And just move settings from webpack config to remote-types.config.json

**Comment by cjh804263197** [comment]
Hi @Abdulaev i think [tar-webpack-plugin](https://github.com/cjh804263197/tar-webpack-plugin) will help you.
### Usage

```javascript
const { ModuleFederationPlugin } = require("webpack").container;
const TarWebpackPlugin = require('tar-webpack-plugin').default;

module.exports = {
    ...
    module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'ts-loader',
          },
          {
            loader: 'dts-loader',
            options: {
              name: 'app2', // The name configured in ModuleFederationPlugin
              exposes: { // The exposes configured in ModuleFederationPlugin
                "./Button": "./src/Button.tsx",
              },
              typesOutputDir: './dist' // Optional, default is '.wp_federation'
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: "app2",
      library: { type: "var", name: "app2" },
      filename: "remoteEntry.js",
      exposes: {
        "./Button": "./src/Button",
      },
      shared: { react: { singleton: true }, "react-dom": { singleton: true } },
    }),
    new TarWebpackPlugin({ // package node-tar as webpack-plugin
      action: 'c', // node-tar method, such as 'c'/'create', 'x'/'extract' 
      gzip: true, // Set to any truthy value to create a gzipped archive, or an object with settings for zlib.Gzip()
      cwd: path.resolve(process.cwd(), 'dist'), // The current working directory for creating the archive. Defaults to process.cwd().
      file: path.resolve(process.cwd(), 'dist', 'app2-ts.tgz'), // Write the tarball archive to the specified filename. If this is specified, then the callback will be fired when the file has been written, and a promise will be returned that resolves when the file is written. If a filename is not specified, then a Readable Stream will be returned which will emit the file data.
      fileList: ['app2'] // an array of paths to add to the tarball. Adding a directory also adds its children recursively.
    })
  ],
}
```
[code example](https://github.com/cjh804263197/test-module-federation/tree/feature/dts-loader)

Hopefully it helped you！

**Comment by jbbelcher53** [comment]
Hey, @Abdulaev I just created a fork and a PR here on this repo that adds the option to automatically create the tarball file with just the loader.

You just need to add the 'tarball' option into the options on the loader and set it to true and it will output the .tgz with your types under .wp_federation or whatever you name the output directory.

@ruanyl When you get a chance if you could take a look at that PR and let me know if it looks good to you that'd be awesome.

**Comment by ruanyl** [comment]
Added a simple example, checkout `examples` folder
