### ISSUE TITLE
Project loads the component but the typings still can't be found

### ISSUE THREAD

**Issue by andrew-rubiano1989** [ruanyl/dts-loader#17]
![image](https://user-images.githubusercontent.com/6477595/194455332-9a0f3f7c-faa7-4692-a57b-e5d129804ff6.png)
![image](https://user-images.githubusercontent.com/6477595/194455490-1ccabba1-dca2-4ac7-8303-a801e632c358.png)

tsconfig.json
```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "paths": {
      "*": [
        "*",
        "types/*"
      ]
    },
  },
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

Thank you so much for this library. I finally got the types from my remote app to correctly copy over from the generated tar file into the host app using your webpack-remote-types-plugin. However typescript is still throwing a compiling error about the declaration file not being found. What am I missing?

Some additional context: The import path is correct. I consoled out `Test` before the return in the function and it shows the react component object. 

repo: https://github.com/andrew-rubiano1989/nx-module-federation-test

**Comment by ruanyl** [comment]
Hi @andrew-rubiano1989, from your repo, I can see the types are downloaded in `types` folder in `app-shell` project.
It looks like you need to specify `baseUrl` in `app-shell` `tsconfig.json` as `.`

**Comment by ruanyl** [comment]
Hi, @andrew-rubiano1989, can you please confirm if the issue was fixed?

**Comment by andrew-rubiano1989** [comment]
Hey sorry for the delayed response, just now getting back to this project. I will verify tonight. I appreciate the help

**Comment by andrew-rubiano1989** [comment]
it worked! thank you so much. i knew it would be such a silly oversight.
