### ISSUE TITLE
Unable to download remote types when publicPath is not auto

### ISSUE THREAD

**Issue by dhawaldarji7** [ruanyl/dts-loader#18]
Hi @ruanyl , great work on this. Wanted to reach out to seek help on one small issue I'm facing while trying to run the example.

The apps work fine when: publicPath is "auto" but gives an error when we give a custom publicPath like "http://localhost:3002/remote".

Any ideas on how to solve this?
![Screen Shot 2022-10-19 at 8 58 23 AM](https://user-images.githubusercontent.com/79489190/196697336-e941cb9a-65e8-4f2c-a9de-5ac3365f2f20.png)

**Comment by ruanyl** [comment]
It looks like the tarball is broken, can you actually manually unzip the file?

**Comment by dhawaldarji7** [comment]
Thanks for the reply. This is what I see in the browser when I try to launch the download link for the tarball.

But I can manually unzip the file. 


![Screen Shot 2022-10-19 at 8 59 34 AM](https://user-images.githubusercontent.com/79489190/196697650-1a989bc5-1622-4838-8200-76981d3dbc91.png)

**Comment by ruanyl** [comment]
That's an HTTP 404, was the correct URL `http://localhost:7002/app2-dts.tgz`?
Can you try the following:
```
new WebpackRemoteTypePlugin({
  remotes: {
    app2: "app2@http://localhost:7002/"
  }
})
```
All `WebpackRemoteTypePlugin` need is an URL pointing to an entry to download the tarball, I should update the `README` to make it more clear(apparently it's misleading atm)

**Comment by dhawaldarji7** [comment]
The above solution works, thank you so much!! 😊 
Is there a way we can serve the file from a different url, for example: http://localhost:7002/remote/app2-dts.tgz or is that currently not possible?

**Comment by ruanyl** [comment]
Depends on where you copy `app2-dts.tgz` to, I cannot see your entire webpack config, but I suppose you have a script to make the tarball and copy it to the public path(dev server root/static folder), if you want to serve the file from `/remote`, then you can just copy the tarball to `/remote` folder

**Comment by dhawaldarji7** [comment]
Got it. Thank you so much! Appreciate the help!
