### ISSUE TITLE
export default support

### ISSUE THREAD

**Issue by denis-heka** [ruanyl/dts-loader#3]
I'm exposing a simple module federated button component that uses ```export default```:
``` javascript
// Button.tsx
...
export default Button;
```
dts-loader creates the following file:
``` javascript
// Button.d.ts
export * from './dts/components/Button/Button';
```

As I understand it, this does not expose default exports, only named exports. So typescript is not picking up types on my remote Button.

One way of fixing might be to change dts-loader to create the following file instead:
``` javascript
// Button.d.ts
export * from './dts/components/Button/Button';
import defaultExport from './dts/components/Button/Button';
export default defaultExport;
```
This handles both named and default export cases. Thoughts?

**Comment by ruanyl** [comment]
@denis-heka try to update to latest version, should be fixed

**Comment by denis-heka** [comment]
Amazing timing thanks @ruanyl . Just tested it, works as expected. Closing ticket
