### ISSUE TITLE
Support for nested exposures

### ISSUE THREAD

**Issue by DenisKent** [ruanyl/dts-loader#4]
Hey, I would like to my MF exposes object to look like:
  ``` javascript
exposes: {
    "./components/Button": "./src/components/Button/Button.tsx",
    "./components/Input": "./src/components/Input/Input.tsx",
    "./utils/time": "./src/utils/time.tsx"
  }
```
It doesn't work as expected, no files are created. When I run a build, I get the following message:
```
Skip lib\src\components\Button\Button.tsx
...
```
1. It might be worth showing the error message within the catch statement so the user knows why something wasn't generated. 
2. The error I'm getting is: ```ENOENT: no such file or directory, open 'lib\dist\lib\components\Button.d.ts'```. It looks to be caused by ``` fs.writeFileSync ```  because the \lib\components directory does not exist. 

https://github.com/ruanyl/dts-loader/blob/621492b4d15d205b3dd89665b44bb7d6b89368c9/src/index.ts#L117-L130

**Comment by ruanyl** [comment]
@DenisKent right, it doesn't expect to have a path as the `exposes` configuration key at the moment. I'll try to look into it

**Comment by DenisKent** [comment]
Thanks @ruanyl . Happy to work on it myself too btw. One thing that makes me hesitate is that I've not found a good way of testing updated code in action. Do you know how one might test a new branch of a webpack loader on a webpack config?

**Comment by fabiomilheiro** [comment]
I faced a similar problem but the resolution is quite simple, actually.
You can refactor your code to look like this:
```js
exposes: {
  "./components/Button": "./src/Button.tsx", // which exports ./src/components/Button/Button.tsx
  "./components/Input": "./src/Input.tsx", // which exports ./src/components/Input/Input.tsx
  "./utils/time": "./src/time.tsx" // which exports ./src/utils/time.tsx
}
```

Hope it helps.

**Comment by ruanyl** [comment]
@DenisKent @fabiomilheiro Thanks for bringing this up, this is now supported in `v0.1.2`
