### ISSUE TITLE
Support for React.forwardRef

### ISSUE THREAD

**Issue by denis-heka** [ruanyl/dts-loader#5]
Hey.

The loader doesn't seem to be working when using React.forwardRef().

e.g. an input component using React.forwardRef()
``` javascript
// components/Input/Input.tsx
import React from "react";

interface IInputProps {
  id: string;
}

const Input = React.forwardRef(({ id }: IInputProps, ref) => {
  return <input ref={ref}/>
});
export default Input;
```
dts-loader creates the file:
``` javascript
// dts/components/Input/Input.dts
declare const Input: any;
export default Input;
```

---------------------------------

If I don't use forwardRef:
``` javascript
// components/Input/Input.tsx
import React from "react";

interface IInputProps {
  id: string;
}

const Input = ({ id }: IInputProps) => {
  return <input />
};
export default Input;
```
dts-loader creates propper typing:
``` javascript
// dts/components/Input/Input.dts
import React from "react";
interface IInputProps {
    id: string;
};
declare const Input: ({ id }: IInputProps) => JSX.Element;
export default Button;
```

Any thoughts on how to solve this? I could simply pass through a ref another way, but this seems like a bug & React.forwardRef() is meant to be best practice. I imagine this will be a common occurrence for people using module federation for UI libraries.

**Comment by ruanyl** [comment]
The `.d.ts` file is generated by the Typescript compiler, I haven't looked into it in detail why it's `any` in this case. But to get the type to generate correctly for your case, one way is to give a bit more instruction to Typescript like this:
```typescript
const Input: React.ForwardRefExoticComponent<
  IInputProps & React.RefAttributes<HTMLInputElement>
> = React.forwardRef(
  ({ id }, ref) => {
    return <input id={id} ref={ref} />
  }
)

```

**Comment by denis-heka** [comment]
Thanks! That solved it! Closing issue. Might be worth deleting since it isn't an issue with this project.
